name: Pip package

on:
  push:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.10"]
          poetry-version: ["1.7.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/prepare
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ matrix.poetry-version }}

      - name: Build package
        run: |
          poetry build

      - name: Install package (optional)
        run: |
          pip install --upgrade dist/*.whl

      - name: Upload to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build -r pypi
