name: Python package build and publish

on:
  push:
  release:
    types: [published]
  workflow_call:
    inputs:
      python-version:
          default: "3.10.4"
          type: string
      poetry-version:
          default: "1.7.1"
          type: string
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/prepare
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}

      - name: Build package
        run: |
          poetry build

      - name: Install package (optional)
        run: |
          pip install --upgrade dist/*

      - name: Upload to PyPI
        if: github.event_name == 'release'
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --build -r pypi -u __token__ -p $PYPI_API_TOKEN --non-interactive
